### ISSUE TITLE
Move several types to pointers

### ISSUE THREAD

**Issue by mperham** [honeybadger-io/honeybadger-go#2]
There's a couple of spots where you are mixing pointers and value types for core types like Configuration and Context.  For instance, your Configuration type is a pointer [here](https://github.com/honeybadger-io/honeybadger-go/blob/master/client.go#L17) but a value [here](https://github.com/honeybadger-io/honeybadger-go/blob/master/client.go#L23), forcing you to awkwardly deference it.  Unless you are explicitly trying for a functional-ish API (i.e. immutable), I'd suggest moving to use pointers exclusively for composite types; it ensures you aren't spending extra cycles copying data needlessly and can mutate method parameters.

**Comment by kostyantyn** [comment]
@joshuap what do you think about using `Configuration` as a pointer everywhere. 

For instance, creating a copy of a client, you could pass the configuration from existing one.
`client := honeybadger.New(oldClient.Config)`

right now you must dereference the pointer:
`client := honeybadger.New(*oldClient.Config)`

What is the reason that `honeybadger.New` accepts `Configuration` as a value and not as a pointer?

**Comment by joshuap** [comment]
I think I can do that; it will just require rebuilding the instances which depend on the configuration when `Configure` is called, otherwise the issue is that the Configuration values change but the objects (like the worker) which already exist don't get the updated values. I'll play with this a bit.

**Comment by joshuap** [comment]
I fixed the issue of dereferencing the config in order to update it. I think we're basically not going the functional route, so this seems simpler.

@kostyantyn regarding passing a value rather than a pointer to things like `honeybadger.Configure()` and `honeybadger.New()`, I did that because the argument in those cases is used to update the pointer config which is created on the returned `Client` instance. Passing a pointer would not reduce the number of copies, and I think `honeybadger.Configure(honeybadger.Configuration{APIKey: "your api key"})` is a simpler API than `honeybadger.Configure(&honeybadger.Configuration{APIKey: "your api key"})` (having to reference a pointer). Thoughts?
